os: osx
osx_image: xcode12.4
language: swift
script: xcodebuild clean build test -workspace Weather\ App.xcworkspace -scheme "Weather App" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO